// Curated open-source conflict dataset (ACLED, Wikipedia, UCDP)
const CONFLICTS_DATA = [
    {
        id: 'ukraine-russia',
        name: 'Russia–Ukraine War',
        region: 'europe',
        country: 'Ukraine',
        lat: 49.0, lng: 31.5,
        intensity: 'critical',
        type: 'Interstate War',
        started: '2022-02-24',
        status: 'Active',
        casualties: '500,000+',
        displaced: '8M+',
        description: 'Full-scale Russian invasion of Ukraine. Frontlines span hundreds of kilometres across eastern and southern Ukraine. NATO members provide extensive military aid.',
        parties: ['Ukraine', 'Russia', 'NATO (support)'],
        tags: ['invasion', 'nato', 'europe', 'nuclear-risk']
    },
    {
        id: 'gaza-israel',
        name: 'Gaza–Israel Conflict',
        region: 'middle-east',
        country: 'Palestine / Israel',
        lat: 31.5, lng: 34.5,
        intensity: 'critical',
        type: 'Armed Conflict',
        started: '2023-10-07',
        status: 'Ceasefire / Active',
        casualties: '52,000+',
        displaced: '1.9M+',
        description: 'Launched after Hamas-led attacks killed ~1,200 Israelis and took ~250 hostages on Oct 7 2023. IDF campaign destroyed large parts of Gaza City, Khan Younis and Rafah. Phase 1 ceasefire agreed Jan 2025 with hostage-for-prisoner exchanges. Humanitarian crisis remains catastrophic: famine-level conditions, hospitals overwhelmed, over 90% of population displaced at peak. Ceasefire fragile; IDF resumed operations in March 2025.',
        parties: ['Israel (IDF)', 'Hamas', 'Palestinian Islamic Jihad', 'UNRWA / Aid Agencies'],
        tags: ['middle-east', 'humanitarian', 'urban-warfare', 'ceasefire', 'hostage-crisis']
    },
    {
        id: 'sudan',
        name: 'Sudan Civil War',
        region: 'africa',
        country: 'Sudan',
        lat: 15.5, lng: 30.0,
        intensity: 'critical',
        type: 'Civil War',
        started: '2023-04-15',
        status: 'Active',
        casualties: '150,000+',
        displaced: '10M+',
        description: 'Armed conflict between the Sudanese Armed Forces (SAF) and Rapid Support Forces (RSF). One of the world\'s worst humanitarian crises with widespread famine.',
        parties: ['SAF', 'RSF'],
        tags: ['civil-war', 'africa', 'famine', 'humanitarian']
    },
    {
        id: 'myanmar',
        name: 'Myanmar Civil War',
        region: 'asia',
        country: 'Myanmar',
        lat: 19.0, lng: 96.5,
        intensity: 'high',
        type: 'Civil War',
        started: '2021-02-01',
        status: 'Active',
        casualties: '50,000+',
        displaced: '2.8M+',
        description: 'Armed conflict following military coup. People\'s Defence Forces, ethnic armed organisations, and resistance groups fight the military junta across the country.',
        parties: ['Military Junta (SAC)', 'PDF / NUG', 'EAOs'],
        tags: ['civil-war', 'coup', 'asia']
    },
    {
        id: 'drc',
        name: 'DRC Eastern Conflict',
        region: 'africa',
        country: 'DR Congo',
        lat: -1.5, lng: 29.0,
        intensity: 'high',
        type: 'Civil War',
        started: '1996-01-01',
        status: 'Active',
        casualties: '6M+ (total)',
        displaced: '7M+',
        description: 'M23 rebel advance backed by Rwanda has captured Goma and large areas of North and South Kivu. Multiple armed groups operate in the east.',
        parties: ['FARDC', 'M23 / RDF', 'FDLR', 'ADF', 'WAZALENDO'],
        tags: ['civil-war', 'africa', 'minerals', 'proxy']
    },
    {
        id: 'ethiopia',
        name: 'Ethiopia Conflicts',
        region: 'africa',
        country: 'Ethiopia',
        lat: 10.5, lng: 38.5,
        intensity: 'high',
        type: 'Civil War',
        started: '2020-11-04',
        status: 'Active',
        casualties: '300,000+',
        displaced: '4M+',
        description: 'Ceasefire in Tigray but violence continues in Amhara (FANO insurgency) and Oromia (OLA). Humanitarian crisis persists across multiple regions.',
        parties: ['Ethiopian Government (ENDF)', 'FANO', 'OLA / OLF'],
        tags: ['civil-war', 'africa', 'humanitarian']
    },
    {
        id: 'somalia',
        name: 'Somalia Insurgency',
        region: 'africa',
        country: 'Somalia',
        lat: 5.5, lng: 46.0,
        intensity: 'high',
        type: 'Insurgency',
        started: '2006-01-01',
        status: 'Active',
        casualties: '500,000+ (total)',
        displaced: '3M+',
        description: 'Al-Shabaab insurgency continues across central and southern Somalia. Regular bombings, assassinations, and ambushes targeting civilians and security forces.',
        parties: ['Somali Government (FGS)', 'ATMIS', 'Al-Shabaab'],
        tags: ['insurgency', 'terrorism', 'africa']
    },
    {
        id: 'sahel',
        name: 'Sahel Jihadist Insurgency',
        region: 'africa',
        country: 'Mali / Burkina Faso / Niger',
        lat: 14.5, lng: -2.0,
        intensity: 'high',
        type: 'Insurgency',
        started: '2012-01-01',
        status: 'Active',
        casualties: '25,000+',
        displaced: '3.5M+',
        description: 'JNIM and ISGS operate across the Sahel. French forces withdrew; Russian Wagner Group replaced them. Burkina Faso under severe jihadist siege.',
        parties: ['JNIM (GSIM)', 'ISGS (ISWAP)', 'Malian Army', 'Wagner/Africa Corps'],
        tags: ['insurgency', 'terrorism', 'africa', 'sahel']
    },
    {
        id: 'yemen',
        name: 'Yemen Civil War & Red Sea Crisis',
        region: 'middle-east',
        country: 'Yemen',
        lat: 15.5, lng: 47.5,
        intensity: 'high',
        type: 'Civil War / Maritime Crisis',
        started: '2014-09-21',
        status: 'Active',
        casualties: '377,000+',
        displaced: '4.5M+',
        description: 'Multi-sided civil war; Houthis (Ansar Allah) control Sanaa and the Red Sea coast. Since late 2023, Houthis have launched hundreds of drone and missile attacks on commercial and military vessels in the Red Sea and Gulf of Aden, disrupting ~12% of global trade. US-UK "Operation Poseidon Archer" conducted hundreds of airstrikes on Houthi infrastructure. Houthis declared a maritime ceasefire linked to Gaza but resumed attacks. Saudi-Houthi peace talks ongoing; ground war largely static.',
        parties: ['Houthis (Ansar Allah)', 'Saudi Coalition', 'Yemeni Government (ROYG)', 'STC', 'US / UK (airstrikes)'],
        tags: ['civil-war', 'middle-east', 'shipping', 'iran-backed', 'red-sea', 'maritime']
    },
    {
        id: 'afghanistan',
        name: 'Afghanistan Conflict',
        region: 'asia',
        country: 'Afghanistan',
        lat: 33.9, lng: 67.7,
        intensity: 'high',
        type: 'Insurgency',
        started: '2021-08-15',
        status: 'Active',
        casualties: 'Unknown',
        displaced: '3.5M+',
        description: 'Taliban governance with ongoing ISIS-Khorasan attacks on mosques, markets, and civilians. Severe humanitarian crisis; women barred from education.',
        parties: ['Taliban (IEA)', 'ISIS-K (ISKP)', 'NRF'],
        tags: ['insurgency', 'terrorism', 'asia', 'humanitarian']
    },
    {
        id: 'nigeria',
        name: 'Nigeria Insurgency',
        region: 'africa',
        country: 'Nigeria',
        lat: 11.0, lng: 13.5,
        intensity: 'high',
        type: 'Insurgency',
        started: '2009-07-26',
        status: 'Active',
        casualties: '350,000+',
        displaced: '2.3M+',
        description: 'Boko Haram and ISWAP insurgency in the Lake Chad Basin. Bandit violence in the northwest and communal conflicts in the Middle Belt add to the crisis.',
        parties: ['Nigerian Military', 'Boko Haram', 'ISWAP', 'Bandits'],
        tags: ['insurgency', 'terrorism', 'africa']
    },
    {
        id: 'syria',
        name: 'Syria Post-War Transition',
        region: 'middle-east',
        country: 'Syria',
        lat: 34.8, lng: 38.8,
        intensity: 'medium',
        type: 'Post-Civil War / Insurgency',
        started: '2011-03-15',
        status: 'Transitional',
        casualties: '500,000+',
        displaced: '13M+',
        description: 'Assad regime fell in December 2024 after HTS-led offensive swept from Idlib to Damascus in 12 days. HTS (Ahmad al-Sharaa / Jolani) leads the new transitional government. SDF controls the northeast under US protection; Turkish-backed SNAF operates in the north and has clashed with SDF. ISIS exploiting the power vacuum with stepped-up attacks in Deir ez-Zor and Homs desert. Reconstruction needs estimated at $400B+; sanctions relief remains contested.',
        parties: ['HTS / New Government (SIG)', 'SDF (AANES)', 'Turkish Forces / SNAF', 'ISIS', 'US Forces'],
        tags: ['civil-war', 'middle-east', 'post-conflict', 'reconstruction', 'isis']
    },
    {
        id: 'haiti',
        name: 'Haiti Gang Crisis',
        region: 'americas',
        country: 'Haiti',
        lat: 18.9, lng: -72.3,
        intensity: 'high',
        type: 'Gang Violence',
        started: '2021-07-07',
        status: 'Active',
        casualties: '5,000+',
        displaced: '700,000+',
        description: 'Armed gangs control 80%+ of Port-au-Prince. Political vacuum after presidential assassination. Kenya-led Multinational Security Support mission deployed.',
        parties: ['Viv Ansanm (Barbeque)', 'Government', 'MSS (Kenya)'],
        tags: ['gang-violence', 'humanitarian', 'americas']
    },
    {
        id: 'pakistan-ttp',
        name: 'Pakistan–TTP Insurgency',
        region: 'asia',
        country: 'Pakistan',
        lat: 33.0, lng: 70.0,
        intensity: 'medium',
        type: 'Insurgency',
        started: '2007-12-14',
        status: 'Active',
        casualties: '80,000+',
        displaced: '1M+',
        description: 'TTP (Tehrik-i-Taliban Pakistan) insurgency in KPK and Balochistan. Attacks increased sharply since 2021. Cross-border clashes with Afghanistan.',
        parties: ['Pakistan Military', 'TTP', 'BLA'],
        tags: ['insurgency', 'terrorism', 'asia']
    },
    {
        id: 'mozambique',
        name: 'Mozambique Insurgency',
        region: 'africa',
        country: 'Mozambique',
        lat: -12.0, lng: 40.5,
        intensity: 'high',
        type: 'Insurgency',
        started: '2017-10-05',
        status: 'Active',
        casualties: '6,000+',
        displaced: '1M+',
        description: 'ISIS-affiliated insurgency in Cabo Delgado province. SAMIM regional forces and private contractors deployed. Rich natural gas fields at stake.',
        parties: ['FADM', 'SAMIM', 'ANSAR al-Sunna (ISIS affiliate)'],
        tags: ['insurgency', 'terrorism', 'africa', 'resources']
    },
    {
        id: 'cameroon',
        name: 'Cameroon Conflicts',
        region: 'africa',
        country: 'Cameroon',
        lat: 6.0, lng: 12.5,
        intensity: 'medium',
        type: 'Multiple',
        started: '2017-10-01',
        status: 'Active',
        casualties: '6,000+',
        displaced: '950,000+',
        description: 'Anglophone separatist conflict in NW/SW regions (Ambazonia). Boko Haram insurgency in the Far North. Both conflicts ongoing simultaneously.',
        parties: ['Government', 'Ambazonian Separatists', 'Boko Haram'],
        tags: ['civil-war', 'insurgency', 'africa']
    },
    {
        id: 'colombia',
        name: 'Colombia Armed Conflict',
        region: 'americas',
        country: 'Colombia',
        lat: 4.5, lng: -74.5,
        intensity: 'medium',
        type: 'Insurgency',
        started: '1964-01-01',
        status: 'Active',
        casualties: '220,000+',
        displaced: '8M+',
        description: 'FARC dissidents (EMC/FARC-EP) and ELN guerrillas continue violence despite negotiations. Drug trafficking and illegal mining fund armed groups.',
        parties: ['Colombian Military', 'FARC Dissidents (EMC)', 'ELN'],
        tags: ['insurgency', 'narco', 'americas']
    },
    {
        id: 'mexico',
        name: 'Mexico Cartel Violence',
        region: 'americas',
        country: 'Mexico',
        lat: 24.0, lng: -104.0,
        intensity: 'medium',
        type: 'Criminal Violence',
        started: '2006-12-11',
        status: 'Active',
        casualties: '450,000+ (total)',
        displaced: '400,000+',
        description: 'Sinaloa Cartel internal war (Chapitos vs. Mayos) and CJNG expansion driving record homicides. Security forces engaged across multiple states.',
        parties: ['Sinaloa Cartel (factions)', 'CJNG', 'Mexican Military'],
        tags: ['cartel', 'narco', 'americas']
    },
    {
        id: 'pkk-turkey',
        name: 'PKK–Turkey Conflict',
        region: 'middle-east',
        country: 'Turkey / Iraq / Syria',
        lat: 37.5, lng: 43.0,
        intensity: 'low',
        type: 'Insurgency',
        started: '1984-08-15',
        status: 'Ceasefire Declared',
        casualties: '40,000+',
        displaced: 'Unknown',
        description: 'PKK leader Abdullah Öcalan called a historic ceasefire and ordered PKK disarmament in February 2025 after talks with Turkish state. PKK formally declared cessation of armed struggle in May 2025. Turkish military operations in northern Iraq (Claw series) ongoing; outcome of disarmament process uncertain. SDF in Syria navigating its future status under the new Syrian government and Turkish pressure.',
        parties: ['Turkey (TSK)', 'PKK', 'YPG / SDF'],
        tags: ['insurgency', 'middle-east', 'nato', 'ceasefire', 'disarmament']
    },
    {
        id: 'car',
        name: 'Central African Republic',
        region: 'africa',
        country: 'CAR',
        lat: 6.6, lng: 20.9,
        intensity: 'medium',
        type: 'Civil War',
        started: '2012-12-10',
        status: 'Active',
        casualties: '50,000+',
        displaced: '2M+',
        description: 'Government supported by Russian Africa Corps (ex-Wagner). CPC rebel coalition controls large rural areas. Civilians caught in crossfire.',
        parties: ['FACA / Government', 'Africa Corps (Russia)', 'CPC Coalition'],
        tags: ['civil-war', 'africa', 'mercenary']
    },
    {
        id: 'lebanon-hezbollah',
        name: 'Lebanon–Israel Conflict',
        region: 'middle-east',
        country: 'Lebanon',
        lat: 33.8, lng: 35.8,
        intensity: 'low',
        type: 'Armed Conflict',
        started: '2023-10-08',
        status: 'Ceasefire',
        casualties: '4,000+',
        displaced: '1.2M+',
        description: 'Cross-border conflict between Israel and Hezbollah escalated into full-scale war in September 2024 after years of skirmishes. Hezbollah senior leadership including Secretary-General Hassan Nasrallah killed in Israeli airstrikes. Ceasefire brokered by US and France in November 2024; IDF conducted a 60-day withdrawal. Hezbollah significantly degraded but retaining arms. Lebanese army deploying to south Lebanon under UNIFIL mandate. Israeli violations reported; reconstruction estimated at $8B+.',
        parties: ['Israel (IDF)', 'Hezbollah', 'Lebanese Army (LAF)', 'UNIFIL'],
        tags: ['middle-east', 'ceasefire', 'iran-backed', 'reconstruction']
    },
    {
        id: 'taiwan-strait',
        name: 'Taiwan Strait Tensions',
        region: 'asia',
        country: 'Taiwan / China',
        lat: 24.0, lng: 120.5,
        intensity: 'tension',
        type: 'Military Tension',
        started: '2022-08-01',
        status: 'Heightened',
        casualties: 'None',
        displaced: 'None',
        description: 'PLA conducts regular military exercises simulating blockade of Taiwan. US-Taiwan arms sales and high-level visits trigger Chinese responses.',
        parties: ['China (PLA)', 'Taiwan (ROC)', 'USA'],
        tags: ['tension', 'asia', 'nuclear-risk', 'maritime']
    },
    {
        id: 'south-china-sea',
        name: 'South China Sea Disputes',
        region: 'asia',
        country: 'South China Sea',
        lat: 13.0, lng: 114.0,
        intensity: 'tension',
        type: 'Territorial Dispute',
        started: '2012-01-01',
        status: 'Active',
        casualties: 'Minimal',
        displaced: 'None',
        description: 'China\'s coast guard and navy clashing with Philippine vessels near Second Thomas Shoal. Vietnam and Malaysia also face Chinese pressure.',
        parties: ['China (CCG / PLA-N)', 'Philippines', 'Vietnam', 'Malaysia'],
        tags: ['tension', 'asia', 'maritime', 'nato-adjacent']
    },
    {
        id: 'iran-regional',
        name: 'Iran Regional Tensions',
        region: 'middle-east',
        country: 'Iran / Region',
        lat: 32.0, lng: 53.5,
        intensity: 'tension',
        type: 'Military Tension',
        started: '2024-01-01',
        status: 'Active',
        casualties: 'Ongoing',
        displaced: 'N/A',
        description: 'Israel and Iran exchanged direct missile and drone strikes for the first time in April and October 2024. Israeli strikes destroyed S-300 air defence systems and targeted nuclear-adjacent sites. Iran\'s proxy network (Hezbollah, Houthis, PMF) has been significantly degraded. Iran accelerating uranium enrichment to 60%+; IAEA access limited. US-Iran nuclear deal negotiations stalled. Risk of Israeli preventive strike on Iranian nuclear facilities remains elevated in 2025.',
        parties: ['Iran (IRGC)', 'Israel', 'USA', 'Hezbollah', 'Houthis', 'PMF (Iraq)'],
        tags: ['tension', 'middle-east', 'nuclear-risk', 'proxy', 'iran-backed']
    },
    {
        id: 'libya',
        name: 'Libya Conflict',
        region: 'africa',
        country: 'Libya',
        lat: 27.0, lng: 17.0,
        intensity: 'low',
        type: 'Frozen Conflict',
        started: '2014-05-16',
        status: 'Frozen',
        casualties: '25,000+',
        displaced: '500,000+',
        description: 'Country split between GNU (Tripoli, west) and LNA/Haftar (east). Regular ceasefire violations but no major offensive. Foreign powers maintain influence.',
        parties: ['GNU (Tripoli)', 'LNA / Haftar', 'Turkey', 'Russia / UAE'],
        tags: ['civil-war', 'frozen-conflict', 'africa', 'oil']
    },
    {
        id: 'iraq-isis',
        name: 'Iraq–Syria ISIS Resurgence',
        region: 'middle-east',
        country: 'Iraq / Syria',
        lat: 33.5, lng: 43.5,
        intensity: 'medium',
        type: 'Insurgency',
        started: '2017-12-01',
        status: 'Active',
        casualties: 'Ongoing',
        displaced: 'Unknown',
        description: 'ISIS exploiting the power vacuum created by Assad\'s fall and reduced US presence to resurge in Syria\'s central desert (Badia region) and Iraq\'s Anbar, Kirkuk and Diyala provinces. Dozens of attacks per month targeting Syrian military convoys, Kurdish forces and civilians. US-led coalition conducting strikes but with reduced ground support. PMF (Iran-backed) units under pressure after leadership assassinations in 2024. New Syrian government struggling to establish security in former ISIS heartland.',
        parties: ['ISIS', 'Iraqi Forces (ISF / PMF)', 'SDF', 'US-led Coalition', 'Syrian Transitional Forces'],
        tags: ['insurgency', 'terrorism', 'middle-east', 'syria', 'iraq']
    },
    {
        id: 'west-bank',
        name: 'West Bank Operations',
        region: 'middle-east',
        country: 'West Bank / Palestine',
        lat: 32.0, lng: 35.25,
        intensity: 'high',
        type: 'Military Operations',
        started: '2023-10-07',
        status: 'Active',
        casualties: '900+',
        displaced: '40,000+',
        description: 'Sustained IDF operations in the West Bank since October 2023. Operation Iron Wall (launched Jan 2025) deployed armoured units, drones and bulldozers into Jenin, Tulkarm and Nur Shams refugee camps. Largest West Bank military operation since the Second Intifada. Palestinian Authority (PA) security forces sidelined. Settler violence surged sharply—hundreds of attacks on Palestinian communities. Demolitions of homes and infrastructure widespread. UN warns of risk of permanent displacement.',
        parties: ['Israel (IDF)', 'Palestinian Resistance Factions', 'Palestinian Authority (PA)', 'Israeli Settlers'],
        tags: ['middle-east', 'humanitarian', 'occupation', 'urban-warfare', 'settler-violence']
    },
    {
        id: 'dprk-tensions',
        name: 'North Korea–Regional Tensions',
        region: 'asia',
        country: 'North Korea / Korean Peninsula',
        lat: 39.5, lng: 127.5,
        intensity: 'tension',
        type: 'Military Tension',
        started: '2022-01-01',
        status: 'Heightened',
        casualties: 'None confirmed',
        displaced: 'None',
        description: 'DPRK deployed an estimated 10,000–15,000 troops to support Russia in Ukraine (confirmed by South Korea, USA, NATO) — marking North Korea\'s direct involvement in a European conflict. Pyongyang test-fired multiple ICBMs and a hypersonic missile in 2024–2025. Kim Jong-un oversaw nuclear warhead miniaturisation demonstrations. South Korea suspended inter-Korean agreements; ROK–US–Japan trilateral exercises intensified. Border tensions at DMZ remain elevated.',
        parties: ['North Korea (KPA)', 'South Korea (ROK)', 'USA', 'Russia (DPRK support)'],
        tags: ['tension', 'asia', 'nuclear-risk', 'icbm', 'dprk']
    }
];

// ─── Helper functions ───────────────────────────────────────────────────────

function filterConflicts(region, intensity, query) {
    return CONFLICTS_DATA.filter(c => {
        const matchRegion    = region    === 'all' || c.region    === region;
        const matchIntensity = intensity === 'all' || c.intensity === intensity;
        const q = (query || '').toLowerCase().trim();
        const matchQuery = !q ||
            c.name.toLowerCase().includes(q) ||
            c.country.toLowerCase().includes(q) ||
            c.description.toLowerCase().includes(q) ||
            c.parties.some(p => p.toLowerCase().includes(q)) ||
            c.tags.some(t => t.toLowerCase().includes(q));
        return matchRegion && matchIntensity && matchQuery;
    });
}

const INTENSITY_ORDER = { critical: 0, high: 1, medium: 2, low: 3, tension: 4 };

function sortByIntensity(list) {
    return [...list].sort((a, b) =>
        (INTENSITY_ORDER[a.intensity] ?? 5) - (INTENSITY_ORDER[b.intensity] ?? 5));
}

function getRegionCounts() {
    const counts = { europe: 0, 'middle-east': 0, africa: 0, asia: 0, americas: 0 };
    CONFLICTS_DATA.forEach(c => { if (counts[c.region] !== undefined) counts[c.region]++; });
    return counts;
}
